from .BaseModel import BaseModel
from .Appointment import Appointment
from .Blog import Blog
from .BlogDescription import BlogDescription
from .Category import Category
from .CategoryDescription import CategoryDescription
from .Certificate import Certificate
from .City import City
from .Company import Company
from .CompanySector import CompanySector
from .Consultant import Consultant
from .Department import Department
from .District import District
from .EducationType import EducationType
from .Faculty import Faculty
from .ForeignLanguage import ForeignLanguage
from .ForeignLanguageLevel import ForeignLanguageLevel
from .Gender import Gender
from .Instructor import Instructor
from .JobInfo import JobInfo
from .JobPost import JobPost
from .JobPostDeparment import JobPostDepartment
from .JobType import JobType
from .Language import Language
from .Lecture import Lecture
from .LectureDescription import LectureDescription
from .MaritalStatus import MaritalStatus
from .Nationality import Nationality
from .Profile import Profile
from .ProfileSocialMedia import ProfileSocialMedia
from .Scholarship import Scholarship
from .Sector import Sector
from .SocialMedia import SocialMedia
from .Student import Student
from .StudentEducationInfo import StudentEducationInfo
from .StudentForeignLanguage import StudentForeignLanguage
from .University import University
