# Generated by Django 3.1.7 on 2021-07-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='city',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='city',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='city',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='district',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='district',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='district',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='district',
            name='uuid',
        ),
    ]
