# Generated by Django 3.1.7 on 2021-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
