# Generated by Django 3.1.7 on 2021-07-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20210726_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pms.profile'),
            preserve_default=False,
        ),
    ]
