# Generated by Django 3.2.4 on 2021-06-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_clinic_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.district'),
        ),
    ]
