# Generated by Django 3.1.7 on 2021-08-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20210823_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='uuid',
        ),
    ]
