# Generated by Django 3.2 on 2021-07-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_auto_20210728_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='keyword',
        ),
    ]
