# Generated by Django 3.2 on 2021-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_remove_notification_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
