# Generated by Django 3.1.7 on 2021-08-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_paymentsituation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkingaccount',
            old_name='payment',
            new_name='remainingDebt',
        ),
        migrations.RenameField(
            model_name='paymentmovement',
            old_name='debtPaidOff',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='paymentmovement',
            old_name='remainingDebt',
            new_name='paymentAmount',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
        migrations.AddField(
            model_name='assay',
            name='taxRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkingaccount',
            name='paymentSituation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.paymentsituation'),
        ),
        migrations.AddField(
            model_name='checkingaccount',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmovement',
            name='paymentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.paymenttype'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
