# Generated by Django 3.1.7 on 2021-08-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_protocol_ispaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmovement',
            name='discount',
        ),
    ]
