# Generated by Django 3.1.7 on 2021-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_remove_paymentmovement_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingaccount',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
