# Generated by Django 3.1.7 on 2021-07-29 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_advertisinglocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('publishStartDate', models.DateField()),
                ('publishEndDate', models.DateField()),
                ('price', models.IntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.advertisinglocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
