# Generated by Django 3.1.7 on 2021-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
