# Generated by Django 3.1.7 on 2021-08-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_checkingaccount_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkingaccount',
            name='date',
        ),
    ]
