# Generated by Django 3.1.7 on 2021-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_remove_checkingaccount_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='taxRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
