# Generated by Django 3.1.7 on 2021-07-30 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_advertising_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('publishStartDate', models.DateField()),
                ('publishEndDate', models.DateField()),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='advertising',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='advertising',
            name='company',
        ),
        migrations.RemoveField(
            model_name='advertising',
            name='publishEndDate',
        ),
        migrations.RemoveField(
            model_name='advertising',
            name='publishStartDate',
        ),
        migrations.AddField(
            model_name='advertising',
            name='height',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertising',
            name='width',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdvertisingLocation',
        ),
        migrations.AddField(
            model_name='companyadvertising',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.advertising'),
        ),
        migrations.AddField(
            model_name='companyadvertising',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.company'),
        ),
    ]
