# Generated by Django 3.1.7 on 2021-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_protocol_taxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='isPrice',
            field=models.BooleanField(default=False),
        ),
    ]
