# Generated by Django 3.1.7 on 2021-08-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='department',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='department',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='department',
            name='uuid',
        ),
    ]
