# Generated by Django 3.1.7 on 2021-08-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_assay_isprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='situation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pms.protocolsituation'),
            preserve_default=False,
        ),
    ]
