# Generated by Django 3.1.7 on 2021-08-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_auto_20210802_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
        migrations.AddField(
            model_name='form',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pms.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
