# Generated by Django 3.1.7 on 2021-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_auto_20210802_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
