# Generated by Django 3.1.7 on 2021-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_auto_20210827_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=None, max_length=1028),
            preserve_default=False,
        ),
    ]
