# Generated by Django 3.1.7 on 2021-08-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='birthDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pms.gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodGroup',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pms.bloodgroup'),
            preserve_default=False,
        ),
    ]
