# Generated by Django 3.1.7 on 2021-08-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_auto_20210802_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.gender'),
        ),
    ]
