# Generated by Django 3.1.7 on 2021-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='endTime',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
