# Generated by Django 3.1.7 on 2021-08-31 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0020_staff_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.clinic'),
            preserve_default=False,
        ),
    ]
