# Generated by Django 3.1.7 on 2021-08-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0023_auto_20210831_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.gender'),
        ),
    ]
