# Generated by Django 3.1.7 on 2021-08-05 14:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0024_auto_20210805_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='assay',
        ),
        migrations.CreateModel(
            name='ProtocolAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.assay')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.protocol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
