# Generated by Django 3.1.7 on 2021-08-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0025_auto_20210805_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='protocol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pms.protocol'),
            preserve_default=False,
        ),
    ]
