# Generated by Django 3.1.7 on 2021-09-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0025_auto_20210901_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientclinic',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='patientclinic',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='patientclinic',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='patientclinic',
            name='uuid',
        ),
    ]
