# Generated by Django 3.1.7 on 2021-08-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0027_medicine_medicinediagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='medicinediagnosis',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='medicinediagnosis',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='medicinediagnosis',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='medicinediagnosis',
            name='uuid',
        ),
    ]
