# Generated by Django 3.1.7 on 2021-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0028_auto_20210806_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profession',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
