# Generated by Django 3.1.7 on 2021-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0030_auto_20210809_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=models.CharField(default=None, max_length=1028),
            preserve_default=False,
        ),
    ]
