# Generated by Django 3.1.7 on 2021-08-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0032_educationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationtype',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='uuid',
        ),
    ]
