# Generated by Django 3.1.7 on 2021-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0034_doctoreducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreducation',
            name='departmentName',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctoreducation',
            name='facultyName',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
