# Generated by Django 3.1.7 on 2021-08-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0035_auto_20210810_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='image',
            field=models.CharField(default=None, max_length=1028),
            preserve_default=False,
        ),
    ]
