# Generated by Django 3.1.7 on 2021-08-10 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0036_prize_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=256)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
