# Generated by Django 3.1.7 on 2021-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0037_doctorarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorarticle',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
