# Generated by Django 2.2.3 on 2019-08-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patlaks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='tcno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
