# Generated by Django 2.2.15 on 2020-08-25 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('isPublish', models.BooleanField()),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('body', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Metin')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('to', models.CharField(blank=True, max_length=1000, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil Resmi')),
                ('mobilePhone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Telefon Numarası')),
                ('gender', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtmek İstemiyorum', 'Belirtmek İstemiyorum')], default='Erkek', max_length=128, verbose_name='Cinsiyeti')),
                ('birthDate', models.DateField(null=True, verbose_name='Doğum Tarihi')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('imei', models.CharField(blank=True, max_length=200, null=True, verbose_name='IMEI')),
                ('gcm_registerID', models.CharField(blank=True, max_length=512, null=True, verbose_name='token')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Doğum Yılı')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şehir')),
                ('notification', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinnedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('blog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booqe.Blog')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booqe.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Mesaj')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booqe.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booqe.Blog')),
                ('whoLike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booqe.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booqe.Blog')),
                ('whoComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booqe.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='category-images/', verbose_name='Category Resim')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booqe.Category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogImage', models.ImageField(blank=True, null=True, upload_to='blog-images/', verbose_name='Blog Resim')),
                ('blog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booqe.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booqe.Profile'),
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='booqe.Category', verbose_name='Kategori'),
        ),
    ]
