# Generated by Django 3.2 on 2021-05-04 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20210417_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdescription',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogdescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogdescription',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='categorydescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorydescription',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='city',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='companysector',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companysector',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foreignlanguagelevel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpostdepartment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobpostdepartment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturedescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturedescription',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='militarystatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militarystatus',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profilesocialmedia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profilesocialmedia',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studenteducationinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studenteducationinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentforeignlanguage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentforeignlanguage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='GenderDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.gender')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('fb840d40-1c1b-4702-b145-4657a4231f12'), editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('foreignLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.foreignlanguage')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
